apiVersion: v1
kind: Pod
metadata:
  name: test-pod-1
  labels:
    name: test-pod-1
spec:
  containers:
  - name: centos
    image: centos
    command: ['sh', 'c', 'sleep 999']
    securityContext:
      privileged: true
    resources:  
      limits:
        memory: "128Mi"
        cpu: "150m"