apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mypvc
spec:
  storageClassName: "apps"
  resources:
    requests:
      storage: "5"
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
